# Generated by Django 5.2.7 on 2025-10-14 09:43

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone]),
        ),
    ]
