# Generated by Django 5.2.7 on 2025-10-14 10:15

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone]),
        ),
    ]
