# Generated by Django 5.2.7 on 2025-10-14 12:09

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_doctor_phone_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(db_index=True, error_messages={'unique': '⚠️ Bu T.C. Kimlik numarası ile zaten bir kayıt var!'}, max_length=11, unique=True, validators=[core.validators.validate_tckn]),
        ),
    ]
