# Generated by Django 5.2.7 on 2025-10-14 12:14

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_patient_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(db_index=True, max_length=11, validators=[core.validators.validate_tckn]),
        ),
    ]
